name: 🌐 Web Builds
on:
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch to use for the builds'
        type: string
      lto:
        description: 'LTO mode. Options: "none", "thin", "full"'
        type: string
      repo:
        description: 'Repository to use for the build'
        default: 'godotengine/godot'
        type: string
      tag:
        description: 'tag to use for the build'
        type: string
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        type: string
      template_module_flags:
        description: 'Extra module flags for template build, e.g. module_webm_enabled=no'
        type: string

# Global Settings
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GODOT_BASE_BRANCH: ${{ inputs.base-branch }}
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no optimize=size use_closure_compiler=yes strict_checks=yes ${{ inputs.module_flags }} use_static_cpp=yes
  EM_VERSION: 4.0.11

jobs:
  web-template:
    runs-on: ubuntu-24.04
    name: 🌐 Web Release Template
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Set up Emscripten latest
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: ${{ env.EM_VERSION }}
          no-cache: true

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: web-template-release-threads-${{ inputs.lto }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} threads=yes arch=wasm32 ${{ inputs.lto }} ${{ inputs.template_module_flags }}
          platform: web
          target: template_release

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: web-template-release-threads-${{ inputs.lto }}
          purge-cache-script: misc/scripts/purge_cache.py
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: web-template-release
          path: bin